CREATE TABLE VEHICLE (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    PLATE VARCHAR(7) NOT NULL,
    MODEL VARCHAR(80) NOT NULL,
    MANUFACTURER VARCHAR(30) NOT NULL,
    COLOR VARCHAR(30),
    STATUS CHAR(1) NOT NULL
) 